---
apiVersion: v1
kind: Service
metadata:
  name: backendservice
spec:
  type: LoadBalancer
  selector:
    app: backendapp
    tier: backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
