---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    appName: yolo
    serverClass : client
    memoryOptimised : "yes"
    component: frontend
  annotations:
    description: "Deployment for frontend application"
spec:
  replicas: 1
  selector:
    matchLabels:
      appName : yolo
      memoryOptimised : "yes" 
      app: yoloclient
      component: frontend
  template:
    metadata:
      labels:
        appName : yolo
        memoryOptimised : "yes"
        app: yoloclient
        component: frontend
    spec:
      containers:
        - name: client
          image: anishadaniels/yoloclient:v1.0.2
          imagePullPolicy: Always
          ports:
            - containerPort: 3000           
          env:
            - name: CLIENT_HOST
              value: "backend-service"
            - name: CLIENT_PORT
              value: "5000"
          
            
      

