---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    app: yoloclient
    component: frontend
  annotations:
    description: "Service for frontend application"
spec:
  type: LoadBalancer
  selector:
    app: yoloclient
    component: frontend
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 3000