apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret-uri
type: Opaque
data:
  MONGODB_URI: "bW9uZ29kYitzcnY6Ly9hbmlzaGFkYW5pZWxzOnlWUzFVY1p5U2tmT3FkbU5AY2x1c3RlcjAub2tmcTA4bC5tb25nb2RiLm5ldC8/cmV0cnlXcml0ZXM9dHJ1ZSZ3PW1ham9yaXR5"
