---
- name: Provision Vagrant VM and set up Docker containers
  hosts: all
  become: true
  vars:
    vm_name: ubuntu-server
    vm_cpus: 2
    vm_memory: 2048
    vm_box: ubuntu/focal64
    app_port: "8000"
    app_name: yolomy
    web_app_dir: /home/vagrant/web_app
    db_password: "yVS1UcZySkfOqdmN"
  tasks:
    - name: Provision Vagrant VM
      block:
        - name: Install VirtualBox Guest Additions
          shell: sudo apt-get install -y virtualbox-guest-additions-iso
          when: ansible_virtualization_type == 'virtualbox'
        - name: Install Vagrant NFS Plugin
          shell: vagrant plugin install vagrant-nfs_guest
          when: ansible_virtualization_type == 'virtualbox'
        - name: Create Vagrantfile
          template:
            src: templates/Vagrantfile.j2
            dest: Vagrantfile
        - name: Start Vagrant virtual machine
          shell: vagrant up --no-provision
          args:
            
        - name: Provision Vagrant virtual machine
          shell: vagrant provision
          args:
            chdir: "{{ playbook_dir }}"
        - name: Add Vagrant SSH key to known_hosts
          shell: ssh-keyscan -H 127.0.0.1 >> ~/.ssh/known_hosts
          args:
            warn: false
        - name: Test SSH connection to Vagrant virtual machine
          shell: ssh -i ~/.vagrant.d/insecure_private_key -o UserKnownHostsFile=/dev/null
            -o StrictHostKeyChecking=no vagrant@127.0.0.1 -p 2222 echo "SSH
            connection successful"
          args:
            warn: false
      tags:
        - vagrant
 